EnableSafeLinksForEmail       = True
EnableSafeLinksForTeams       = True
EnableSafeLinksForOffice      = True
TrackClicks                   = True
AllowClickThrough             = False
ScanUrls                      = True
EnableForInternalSenders      = True
DeliverMessageAfterScan       = True
DisableUrlRewrite             = False
DoNotRewriteUrls              = {}
LocalizedNotificationTextList = {}
EnableOrganizationBranding    = False
Name                          = Custom Standard Preset Security Policy